spring:
  application:
    name: todo

  # 데이터베이스 연결을 위한 설정
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: TODO
    password: 1234
  
  # JSP를 사용하기 위해 JSP 파일들의 경로를 설정. -> WebConfig.java로 설정 이동함(Spring Validator 사용으로 인한 변경)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# mybatis 설정 파일의 경로 지정
mybatis:
  # mybatis-config.xm 파일의 위치를 지정한다.
  config-location: classpath:mybatis/mybatis-config.xml
  # **로 패턴매칭(원래는 bbs), *로 Mapper패턴매칭(원래는 BoardDao) -> Mapper.xml로 끝나는 모든 것을 찾아라.
  mapper-locations: classpath:com/ktdsuniversity/edu/todo/dao/mapper/*Mapper.xml
